### ISSUE TITLE
Error for failed generation missing a message for the user

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern-typescript#219]
TypeScript SDK generator failed without a human-readable error message as to what I can do to fix it.

```
ERROR 2022-12-26T22:12:55.430Z [primer-api]: fernapi/fern-typescript-sdk Failed to tag 0.0.24 on repo: fern-primer/primer-node
ERROR 2022-12-26T22:12:55.430Z [primer-api]: fernapi/fern-typescript-sdk Failed.
ERROR 2022-12-26T22:12:55.431Z [primer-api]: fernapi/fern-typescript-sdk Failed.
ERROR 2022-12-26T22:12:55.432Z Error
                                   at CliContext.runTaskWithInit (/home/runner/.npm/_npx/a1c2d786771b58cc/node_modules/fern-api/bundle.cjs:131823:13)
                                   at processTicksAndRejections (node:internal/process/task_queues:96:5)
                                   at async CliContext.runTaskForWorkspace (/home/runner/.npm/_npx/a1c2d786771b58cc/node_modules/fern-api/bundle.cjs:131809:5)
                                   at async Promise.all (index 0)
                                   at async generateWorkspaces (/home/runner/.npm/_npx/a1c2d786771b58cc/node_modules/fern-api/bundle.cjs:135280:3)
                                   at async Object.handler (/home/runner/.npm/_npx/a1c2d786771b58cc/node_modules/fern-api/bundle.cjs:136806:7)
```

**Comment by dannysheridan** [comment]
closing as stale
